Added Wishlist model, repository, service, and service implementation files.
pabloehc/cen4010-team-9-bookstore pull request #5
Opened 2023-06-11 23:06 UTC by MyNameJavi

Added Wishlist model, repository, service, and service implementation files.

2023-06-11 23:08 UTC, pabloehc approved these changes

2023-06-11 23:18 UTC, Mherr162 reviewed
only Add @Service above your WishlisServiceImpl class

2023-06-11 23:18 UTC, Mherr162 commented on src/main/java/bookstore/service/impl/WishlistServiceImpl.java
> +
Add @Service

2023-06-11 23:33 UTC, pabloehc requested changes
Address @Mherr162 comment

2023-06-12 00:16 UTC, pabloehc approved these changes

2023-06-12 00:17 UTC, merged